environment:
  name: Staging Environment
  identifier: staging
  description: Staging environment for pre-production testing
  type: PreProduction
  tags:
    environment: staging
    team: qa
  variables:
    - name: ssh_user
      type: String
      description: SSH user for connecting to staging servers
      value: deploy-staging
    - name: db_host
      type: String
      description: Database host for staging
      value: staging-db.internal.com
    - name: app_port
      type: String
      description: Application port
      value: "8080"
    - name: log_level
      type: String
      description: Application log level
      value: INFO
  overrides:
    manifests: []
    configFiles: []
    variables: []